version: "3.7"

networks:
  reverse-proxy:
    external: true

services:
  service:
    build:
      context: .
      args:
        uid: ${UID}
    container_name: sebn-brettbau-warehouse
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    # ports:
    #   - "8080:8080"
    networks:
      reverse-proxy:
        aliases:
          - sebn-brettbau-warehouse
volumes:
  sebn-brettbau-warehouse:
